version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.10
    steps:

      # prep the system
      - restore_cache:
          keys:
            - "v1-apt"

      - run:
          name: "apt-get update"
          command: "apt-get update"
      - run:
          name: "apt-get install"
          command: "apt-get install -y ca-certificates emacs-nox make wget ssh git curl"

      - restore_cache:
          keys:
            - "v1-dot-git"

      - checkout

      - restore_cache:
          keys:
            - "v1-checkdoc-batch-el"

      - run:
          name: "make"
          command: "make _circleci_run"

      - store_artifacts:
          path: "checkdoc.stderr"
      - store_artifacts:
          path: "checkdoc.stdout"
      - store_artifacts:
          path: "junit.xml"

      # save a bunch of stuff.
      - save_cache:
          key: "v1-apt"
          paths:
            - "/var/cache/apt/archives"
      - save_cache:
          key: "v1-dot-git"
          paths:
            - ".git"
      - save_cache:
          key: "v1-checkdoc-batch-el"
          paths:
            - "checkdoc-batch.el"
